Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/bionic64" 
  config.vm.box_url = "https://vagrantcloud.com/hashicorp/bionic64"

  config.vm.define "pdolS" do |control|
    control.vm.hostname = "pdolS"
    control.vm.network "private_network", ip: "192.168.56.110"
    control.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.cpus = 1
      v.customize ["modifyvm", :id, "--name", "pdolS"]
    end
    config.vm.provision "shell", path: "controller-installer.sh"
  end
  config.vm.define "pdolSW" do |control|
    control.vm.hostname = "pdolSW"
    control.vm.network "private_network", ip: "192.168.56.111"
    control.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.cpus = 1
      v.customize ["modifyvm", :id, "--name", "pdolSW"]
    end
    config.vm.provision "shell", path: "agent-installer.sh"
  end
end
