Vagrant.configure(2) do |config|
  config.vm.box = "rockylinux/9" 

  config.vm.define "pS" do |server|
    server.vm.hostname = "pS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.cpus = 1
      v.customize ["modifyvm", :id, "--name", "pS"]
    end
    server.vm.provision "shell", path: "server-installer.sh"
  end

  config.vm.define "pSW" do |agent|
    agent.vm.hostname = "pSW"
    agent.vm.network "private_network", ip: "192.168.56.111"
    agent.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.cpus = 1
      v.customize ["modifyvm", :id, "--name", "pSW"]
    end
    agent.vm.provision "shell", path: "agent-installer.sh"
  end
end
